<?php
namespace wpdev;

include_once dirname(__DIR__) . '/classes/class-admin.php';
include_once dirname(__DIR__) . '/classes/class-asset.php';
include_once dirname(__DIR__) . '/classes/class-base.php';
include_once dirname(__DIR__) . '/classes/class-comment.php';
include_once dirname(__DIR__) . '/classes/class-customizer.php';
include_once dirname(__DIR__) . '/classes/class-dashboard.php';
include_once dirname(__DIR__) . '/classes/class-environment.php';
include_once dirname(__DIR__) . '/classes/class-app.php';
include_once dirname(__DIR__) . '/classes/class-api-key.php';
include_once dirname(__DIR__) . '/classes/class-docs.php';
include_once dirname(__DIR__) . '/classes/class-editor.php';
include_once dirname(__DIR__) . '/classes/class-hardening.php';
include_once dirname(__DIR__) . '/classes/class-image.php';
include_once dirname(__DIR__) . '/classes/class-log.php';
include_once dirname(__DIR__) . '/classes/class-login.php';
include_once dirname(__DIR__) . '/classes/class-menu.php';
include_once dirname(__DIR__) . '/classes/class-plugin.php';
include_once dirname(__DIR__) . '/classes/class-post.php';
include_once dirname(__DIR__) . '/classes/class-redirect.php';
include_once dirname(__DIR__) . '/classes/class-rest.php';
include_once dirname(__DIR__) . '/classes/class-role.php';
include_once dirname(__DIR__) . '/classes/class-screens.php';
include_once dirname(__DIR__) . '/classes/class-site.php';
include_once dirname(__DIR__) . '/classes/class-site-health.php';
include_once dirname(__DIR__) . '/classes/class-status.php';
include_once dirname(__DIR__) . '/classes/class-support.php';
include_once dirname(__DIR__) . '/classes/class-toolbar.php';
include_once dirname(__DIR__) . '/classes/class-webhook.php';
